name: mini-all
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scipy
  - notebook
  - ipywidgets
  - tk
  - pytest
  - pip
  - pip:
      - nbformat
